# Uncomment the next line to define a global platform for your project
source 'https://git.coding.net/CocoaPods/Specs.git'

 platform :ios, '9.0'

 target 'Block--Demo' do
 
 pod 'AFNetworking' , '~> 3.1.0'
 pod 'SDWebImage', '~> 4.0.0'

end

